Repository prgmr99/WindowFormIsCrazy, pull requests merged in 2023-06, with the labels that each got.

#42 [Feat] #38 - Result Screen UI 구현 및 ConvertAPI 적용
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Data/ConvertRequest.cs
  ConvertGPT/ConvertGPT/Global/ConvertGPTGlobal.cs
  ConvertGPT/ConvertGPT/Network/Deprecated/GPTTest.cs
  ConvertGPT/ConvertGPT/Network/Type/ConvertType.cs
  ConvertGPT/ConvertGPT/Presentation/Common/LanguageForm.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/DragForm.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/DragForm.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/GuideScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/HomeScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/HomeScreen.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
  ConvertGPT/ConvertGPT/Properties/Resources.Designer.cs
  ConvertGPT/ConvertGPT/Properties/Resources.resx
  ConvertGPT/ConvertGPT/Resource/Icon/icon_bulb.png
  ConvertGPT/ConvertGPT/Resource/Icon/icon_copy.png
  ConvertGPT/ConvertGPT/Resource/Icon/icon_refresh.png
Labels: 석우

#45 Mod/#43 MainForm -> DragForm 코드 이동
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Network/Deprecated/GPTTest.cs
  ConvertGPT/ConvertGPT/Presentation/DragForm.cs
  ConvertGPT/ConvertGPT/Presentation/MainForm.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
Labels: 승준

#44 [Feat] #39 - ExplainAPI 구현
  ConvertGPT/ConvertGPT/Application/App.config
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Data/ConvertRequest.cs
  ConvertGPT/ConvertGPT/Data/ConvertResponse.cs
  ConvertGPT/ConvertGPT/Data/ExplainRequest.cs
  ConvertGPT/ConvertGPT/Data/ExplainResponse.cs
  ConvertGPT/ConvertGPT/Network/Type/ExplainType.cs
  ConvertGPT/ConvertGPT/Presentation/Common/LanguageForm.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/Common/LanguageForm.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/HomeScreen.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
  ConvertGPT/ConvertGPT/packages.config
Labels: 석우

#48 [Feat] CodeTextBox 구현 #40
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Global/Component/CodeTextBox.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
  ConvertGPT/ConvertGPT/Resource/Icon/icon_check.png
Labels: 대원

#54 [Fix] History, Favorite DB error 수정
  ConvertGPT/ConvertGPT/Presentation/FavoriteScene/FavoriteScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/FavoriteScene/FavoriteScreen.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryScreen.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
Labels: 승준

#57 [Add] explain code, current time column 추가
  ConvertGPT/ConvertGPT/Presentation/DatabaseScene/DatabaseScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/DatabaseScene/DatabaseScreen.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryScreen.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
Labels: 승준

#52 [Feat] #49 Add KeySyntax
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Data/KeySyntaxRequest.cs
  ConvertGPT/ConvertGPT/Network/Interface/IPromptType.cs
  ConvertGPT/ConvertGPT/Network/Service/PromptService.cs
  ConvertGPT/ConvertGPT/Network/Type/ConvertType.cs
  ConvertGPT/ConvertGPT/Network/Type/DBDiagramType.cs
  ConvertGPT/ConvertGPT/Network/Type/ExplainType.cs
  ConvertGPT/ConvertGPT/Network/Type/KeySyntaxType.cs
Labels: 계현

#58 [Feat] #55 Add Extract DB Schema
  ConvertGPT/ConvertGPT/App.config
  ConvertGPT/ConvertGPT/Application/App.config
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Network/Type/DBDiagramType.cs
  ConvertGPT/ConvertGPT/packages.config
Labels: 계현

#62 [Feat] #59 Add BugFixer
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Data/BugFixRequest.cs
  ConvertGPT/ConvertGPT/Network/Type/BugFixType.cs
Labels: 계현

#61 [Feat] #47 - History UI구현 및 DB 데이터 바인딩
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/Data/HistoryModel.cs
  ConvertGPT/ConvertGPT/Global/ConvertGPTGlobal.cs
  ConvertGPT/ConvertGPT/Presentation/Common/KeySyntaxResultForm.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/Common/KeySyntaxResultForm.cs
  ConvertGPT/ConvertGPT/Presentation/Common/KeySyntaxResultForm.resx
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryCell.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryCell.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryCell.resx
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryResultScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryResultScreen.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryResultScreen.resx
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryScreen.Designer.cs
  ConvertGPT/ConvertGPT/Presentation/HistoryScene/HistoryScreen.cs
  ConvertGPT/ConvertGPT/Presentation/MainForm.cs
  ConvertGPT/ConvertGPT/Presentation/MainScene/ResultScreen.cs
Labels: 석우
