Repository prgmr99/WindowFormIsCrazy, pull requests merged in 2023-05, with the labels that each got.

#16 [Feat] 코드 변환 API 구현 #15
  ConvertGPT/.vs/ConvertGPT/v17/.suo
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/ConvertGPT.csproj.user
  ConvertGPT/ConvertGPT/Error/ConvertGPTException.cs
  ConvertGPT/ConvertGPT/Error/ErrorCode.cs
  ConvertGPT/ConvertGPT/Form1.Designer.cs
  ConvertGPT/ConvertGPT/Form1.cs
  ConvertGPT/ConvertGPT/GPTTest.cs
  ConvertGPT/ConvertGPT/MainForm.Designer.cs
  ConvertGPT/ConvertGPT/MainForm.cs
  ConvertGPT/ConvertGPT/MainForm.resx
  ConvertGPT/ConvertGPT/Program.cs
  ConvertGPT/ConvertGPT/bin/Debug/ConvertGPT.exe
  ConvertGPT/ConvertGPT/bin/Debug/ConvertGPT.pdb
  ConvertGPT/ConvertGPT/obj/Debug/ConvertGPT.MainForm.resources
  ConvertGPT/ConvertGPT/obj/Debug/ConvertGPT.csproj.CoreCompileInputs.cache
  ConvertGPT/ConvertGPT/obj/Debug/ConvertGPT.csproj.FileListAbsolute.txt
  ConvertGPT/ConvertGPT/obj/Debug/ConvertGPT.csproj.GenerateResource.cache
  ConvertGPT/ConvertGPT/obj/Debug/ConvertGPT.exe
  ConvertGPT/ConvertGPT/obj/Debug/ConvertGPT.pdb
  ConvertGPT/ConvertGPT/obj/Debug/DesignTimeResolveAssemblyReferences.cache
Labels: 석우

#25 [Feat] 프로그래밍 언어별 코드 색상 구현 #22
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/MainForm.Designer.cs
  ConvertGPT/ConvertGPT/MainForm.cs
  ConvertGPT/ConvertGPT/packages.config
Labels: 대원

#26 [Feat] Copy 버튼 기능 및 반응 추가 #24
  ConvertGPT/ConvertGPT/MainForm.Designer.cs
  ConvertGPT/ConvertGPT/MainForm.cs
Labels: 대원

#30 PromptService,PromptType 추가
  ConvertGPT/ConvertGPT/ConvertGPT.csproj
  ConvertGPT/ConvertGPT/MainForm.cs
  ConvertGPT/ConvertGPT/PromptService/Convert.cs
  ConvertGPT/ConvertGPT/PromptService/DBDiagram.cs
  ConvertGPT/ConvertGPT/PromptService/Explain.cs
  ConvertGPT/ConvertGPT/PromptService/Interface/IPromptService.cs
  ConvertGPT/ConvertGPT/PromptService/Interface/IPromptType.cs
  ConvertGPT/ConvertGPT/PromptService/PromptService.cs
  ConvertGPT/ConvertGPT/PromptService/PromptToImageService.cs
  ConvertGPT/ConvertGPT/packages.config
Labels: 계현
